#!/bin/bash

is_num () {
    egrep -q '^[0-9]+$' <<< $1 && return 0 || return 1
}

is_year () {
    local year=$1
    is_num $year || return 2
    (($year % 400 == 0 || $year % 4  == 0 && $year % 100 != 0)) \
        && return 0 || return 1
}

count_year_day () {
    local startYear=$1 endYear=$2 days=0
    is_num $endYear || return 2
    (( startYear > endYear)) && echo "输入的年份不对， 必须要大于1900年" && return 3
    while [ $startYear -lt $endYear ]; do
        is_year $startYear && let days+=366 || let days+=365
        let startYear++
    done
    echo $days
}
